task: KITTI
exp_name: '3d-object'
map: 'Town_10HD_opt'

collector_module: lib.collectors.KITTI3D
client_module: lib.clients.KITTI3D

carla:
    fixed_delta_seconds: 0.05
    num_of_vehicles: 10 
    num_of_walkers: 20

ego_vehicle:
    blueprint: vehicle.lincoln.*

sensors:
    rgb:
        transform: {location: [0, 0, 1.6], rotation: [0, 0, 0]}
        blueprint: sensor.camera.rgb
        attribute: {image_size_x: 720, image_size_y: 360, fov: 90}

    depth_rgb:
        transform: { location: [ 0, 0, 1.6 ], rotation: [ 0, 0, 0 ] }
        blueprint: sensor.camera.depth
        attribute: { image_size_x: 720, image_size_y: 360, fov: 90 }

    lidar:
        transform: { location: [ 0, 0, 1.6 ], rotation: [ 0, 0, 0 ] }
        blueprint: sensor.lidar.ray_cast
        attribute: {range: 70, rotation_frequency: 20, lower_fov: -45, points_per_second: 1280000, channels: 64}

all_frame_iter: 100
save_frame_iter: 2
