task: base
exp_name: '3d-object'
map: 'Town10HD_Opt'

collector_module: lib.collectors.Basic
client_module: lib.clients.Basic

carla:
    weather: carla.WeatherParameters.ClearNoon
    fixed_delta_seconds: 0.05
    num_of_vehicles: 10 
    num_of_walkers: 20

ego_vehicle:
    blueprint: vehicle.lincoln.*

sensors:
    rgb:
        transform: {location: [0, 0, 1.6], rotation: [0, 0, 0]}
        blueprint: sensor.camera.rgb
        attribute: {image_size_x: 720, image_size_y: 360, fov: 90}

all_frame_iter: 100
