parent_cfg: 'configs/basic.yaml'
task: KITTI
exp_name: '3d-lidar'
map: 'Town03'

collector_module: lib.collectors.KITTI.KITTILidar
client_module: lib.clients.KITTI.KITTILidar

carla:
    weather: WetNoon
    fixed_delta_seconds: 0.05
    num_of_npc_vehicles: 10
    num_of_npc_walkers: 0

ego_vehicle:
    blueprint: vehicle.tesla.model3
    ignore_lights_percentage: 100.0
    ignore_signs_percentage: 100.0
    ignore_vehicles_percentage: 0.0
    ignore_walkers_percentage: 0.0
    vehicle_percentage_speed_difference: 0.0

sensors:
    rgb:
        transform: {location: [0, 0, 1.8], rotation: [0, 0, 0]}
        blueprint: sensor.camera.rgb
        attribute: {image_size_x: 720, image_size_y: 360, fov: 90}

    depth_1:
        transform: { location: [ 0, 0, 1.8 ], rotation: [ 0, -90, 0 ] }
        blueprint: sensor.camera.depth
        attribute: { image_size_x: 720, image_size_y: 360, fov: 90 }
          
    depth_2:
        transform: { location: [ 0, 0, 1.8 ], rotation: [ 0, 0, 0 ] }
        blueprint: sensor.camera.depth
        attribute: { image_size_x: 720, image_size_y: 360, fov: 90 }

    depth_3:
        transform: { location: [ 0, 0, 1.8 ], rotation: [ 0, 90, 0 ] }
        blueprint: sensor.camera.depth
        attribute: { image_size_x: 720, image_size_y: 360, fov: 90 }

    depth_4:
        transform: { location: [ 0, 0, 1.8 ], rotation: [ 0, 180, 0 ] }
        blueprint: sensor.camera.depth
        attribute: { image_size_x: 720, image_size_y: 360, fov: 90 }

    lidar:
        transform: { location: [ 0, 0, 1.8 ], rotation: [ 0, 0, 0 ] }
        blueprint: sensor.lidar.ray_cast
        attribute: {lower_fov: -15, upper_fov: 15, points_per_second: 1280000, channels: 256, rotation_frequency: 20, range: 80,
                    dropoff_general_rate: 0.0, dropoff_intensity_limit: 1.0, dropoff_zero_intensity: 0.0}

all_frame_iter: 1000
